site_name: My Docs

theme:
  name: material
  features:
    # - navigation.tabs
    # - navigation.sections
    # - navigation.footer
    # - toc.integrate
    # - navigation.top
    # - search.suggest
    # - search.highlight
    # - content.tabs.link
    # - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: blue 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: blue
  
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Martin-Reyes7
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/martin-reyes-jaramillo

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/Martin-Reyes7"  target="_blank" rel="noopener">Martin Reyes Jaramillo</a>
